/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemasolicitudes;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author digitacion-6
 */
public class JDNuevoUsuario extends javax.swing.JDialog {
int x,y;
String tipdoc, nom, apePat, apeMat, depart, prov, distr, direc, dni;
    int sol;
    conexion con= new conexion();
    /**
     * Creates new form JDNuevoUsuario
     */
    public JDNuevoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.txtNumDoc.setText(JFPrincipal.DNI);
        panel1.setColorPrimario(new Color(118,130,142, 10));
       
        this.txtApePat.requestFocus();
    }
      public void dbcbox(String sql,JComboBox a){
            try {
                con.conectar();
                ResultSet rs = con.consulta(sql);
                while(rs.next()){
                    a.addItem (rs.getObject(1));
                }
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Error" +e);
            }
        }
    public void nuevoRegistro(){
        int solic=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT COUNT(codUsu) AS num FROM usuarios");
                res.next();
                solic=Integer.parseInt(res.getString("num"));
            }catch(SQLException e){
                System.out.println(e);
            }
        lblUsu.setText(String.valueOf(solic+1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBackgroundTitle1 = new org.edisoncor.gui.label.LabelBackgroundTitle();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panel2 = new org.edisoncor.gui.panel.Panel();
        BtnClose = new org.edisoncor.gui.button.ButtonColoredAction();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        txtNom = new javax.swing.JTextField();
        txtApePat = new javax.swing.JTextField();
        txtApeMat = new javax.swing.JTextField();
        txtNumDoc = new javax.swing.JTextField();
        cboxTipoDocum = new javax.swing.JComboBox();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric9 = new org.edisoncor.gui.label.LabelMetric();
        cboxDepart = new javax.swing.JComboBox();
        cboxProv = new javax.swing.JComboBox();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        cboxDist = new javax.swing.JComboBox();
        txtDirec = new javax.swing.JTextField();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        panel1 = new org.edisoncor.gui.panel.Panel();
        BtnGuardar = new org.edisoncor.gui.button.ButtonColoredAction();
        BtnCancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        lblUsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(666666, 666666));
        setMinimumSize(new java.awt.Dimension(848, 326));
        setPreferredSize(new java.awt.Dimension(848, 326));
        setResizable(false);

        panelImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/captura-rojo.png"))); // NOI18N
        panelImage1.setMaximumSize(new java.awt.Dimension(666, 324));
        panelImage1.setMinimumSize(new java.awt.Dimension(666, 324));
        panelImage1.setPreferredSize(new java.awt.Dimension(666, 324));

        panel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(176, 177, 178)));
        panel2.setColorPrimario(new java.awt.Color(234, 9, 9));
        panel2.setColorSecundario(new java.awt.Color(1, 1, 1));
        panel2.setPreferredSize(new java.awt.Dimension(276, 23));
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });

        BtnClose.setBackground(new java.awt.Color(255, 0, 0));
        BtnClose.setText("x");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        labelMetric1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric1.setText("REGISTRAR NUEVO USUARIO");
        labelMetric1.setDistanciaDeSombra(2);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(BtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMetric1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelCurves1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));

        txtNom.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        txtNom.setMaximumSize(new java.awt.Dimension(146, 21));
        txtNom.setMinimumSize(new java.awt.Dimension(146, 21));
        txtNom.setPreferredSize(new java.awt.Dimension(146, 21));
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });

        txtApePat.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtApePat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        txtApePat.setMaximumSize(new java.awt.Dimension(70, 21));
        txtApePat.setMinimumSize(new java.awt.Dimension(70, 21));
        txtApePat.setPreferredSize(new java.awt.Dimension(70, 21));
        txtApePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApePatKeyPressed(evt);
            }
        });

        txtApeMat.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtApeMat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        txtApeMat.setMaximumSize(new java.awt.Dimension(70, 21));
        txtApeMat.setMinimumSize(new java.awt.Dimension(70, 21));
        txtApeMat.setPreferredSize(new java.awt.Dimension(70, 21));
        txtApeMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApeMatKeyPressed(evt);
            }
        });

        txtNumDoc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNumDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        txtNumDoc.setMaximumSize(new java.awt.Dimension(201, 25));
        txtNumDoc.setMinimumSize(new java.awt.Dimension(201, 25));
        txtNumDoc.setPreferredSize(new java.awt.Dimension(201, 25));
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });

        cboxTipoDocum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxTipoDocum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "D.N.I.", "L.M.", "PASAPORTE" }));
        cboxTipoDocum.setMaximumSize(new java.awt.Dimension(146, 25));
        cboxTipoDocum.setMinimumSize(new java.awt.Dimension(146, 25));
        cboxTipoDocum.setPreferredSize(new java.awt.Dimension(146, 25));
        cboxTipoDocum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxTipoDocumKeyPressed(evt);
            }
        });

        labelMetric2.setText("Tipo de Doc.:");
        labelMetric2.setDistanciaDeSombra(2);

        labelMetric5.setText("Nombres:");
        labelMetric5.setDistanciaDeSombra(2);

        labelMetric9.setText("Departamento:");
        labelMetric9.setDistanciaDeSombra(2);

        cboxDepart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxDepart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AMAZONAS", "ANCASH", "APURIMAC", "AREQUIPA", "AYACUCHO", "CAJAMARCA", "CALLAO", "CUSCO", "HUANCAVELICA", "HUANUCO", "ICA", "JUNIN", "LA LIBERTAD", "LAMBAYEQUE", "LIMA", "LORETO", "MADRE DE DIOS", "MOQUEGUA", "PASCO", "PIURA", "PUNO", "SAN MARTIN", "TACNA", "TUMBES", "UCAYALI" }));
        cboxDepart.setMaximumSize(new java.awt.Dimension(146, 25));
        cboxDepart.setMinimumSize(new java.awt.Dimension(146, 25));
        cboxDepart.setPreferredSize(new java.awt.Dimension(146, 25));
        cboxDepart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxDepartItemStateChanged(evt);
            }
        });
        cboxDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDepartActionPerformed(evt);
            }
        });
        cboxDepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxDepartKeyPressed(evt);
            }
        });

        cboxProv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxProv.setMaximumSize(new java.awt.Dimension(146, 25));
        cboxProv.setMinimumSize(new java.awt.Dimension(146, 25));
        cboxProv.setName(""); // NOI18N
        cboxProv.setPreferredSize(new java.awt.Dimension(146, 25));
        cboxProv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxProvItemStateChanged(evt);
            }
        });
        cboxProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxProvActionPerformed(evt);
            }
        });
        cboxProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxProvKeyPressed(evt);
            }
        });

        labelMetric7.setText("Provincia:");
        labelMetric7.setDistanciaDeSombra(2);

        labelMetric6.setText("Distrito:");
        labelMetric6.setDistanciaDeSombra(2);

        cboxDist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxDist.setMaximumSize(new java.awt.Dimension(146, 25));
        cboxDist.setMinimumSize(new java.awt.Dimension(146, 25));
        cboxDist.setPreferredSize(new java.awt.Dimension(146, 25));
        cboxDist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxDistKeyPressed(evt);
            }
        });

        txtDirec.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtDirec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        txtDirec.setMaximumSize(new java.awt.Dimension(298, 25));
        txtDirec.setMinimumSize(new java.awt.Dimension(298, 25));
        txtDirec.setPreferredSize(new java.awt.Dimension(298, 25));
        txtDirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecActionPerformed(evt);
            }
        });
        txtDirec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDirecKeyPressed(evt);
            }
        });

        labelMetric8.setText("Direccion:");
        labelMetric8.setDistanciaDeSombra(2);

        labelMetric3.setText("A. Paterno:");
        labelMetric3.setDistanciaDeSombra(2);

        labelMetric4.setText("A. Materno:");
        labelMetric4.setDistanciaDeSombra(2);

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addComponent(cboxTipoDocum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxProv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxDist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxTipoDocum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxProv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxDist, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        panel1.setColorPrimario(new java.awt.Color(118, 130, 142));

        BtnGuardar.setBackground(new java.awt.Color(35, 168, 211));
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(242, 17, 28));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(panelImage1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed
        x=evt.getX(); y=evt.getY();
    }//GEN-LAST:event_panel2MousePressed

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged
        Point point=MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x, point.y-y);
    }//GEN-LAST:event_panel2MouseDragged

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtApePat.requestFocus();
        }
    }//GEN-LAST:event_txtNomKeyPressed

    private void txtApePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApePatKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtApeMat.requestFocus();
        }
    }//GEN-LAST:event_txtApePatKeyPressed

    private void txtApeMatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApeMatKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxTipoDocum.requestFocus();
        }
    }//GEN-LAST:event_txtApeMatKeyPressed

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxDepart.requestFocus();
        }
    }//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            cboxDepart.requestFocus();
        }
    }//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void cboxTipoDocumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxTipoDocumKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtNumDoc.requestFocus();
        }
    }//GEN-LAST:event_cboxTipoDocumKeyPressed

    private void cboxDepartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxDepartItemStateChanged
        int valor = this.cboxDepart.getSelectedIndex();
        cboxProv.removeAllItems();
        try{
            dbcbox("SELECT Des_pvi opcion FROM provincias WHERE Cod_dpt="+valor+"0000",cboxProv);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cboxDepartItemStateChanged

    private void cboxDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDepartActionPerformed

    }//GEN-LAST:event_cboxDepartActionPerformed

    private void cboxDepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxDepartKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxProv.requestFocus();
        }
    }//GEN-LAST:event_cboxDepartKeyPressed

    private void cboxProvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxProvItemStateChanged
      String provi = String.valueOf(cboxProv.getSelectedItem());
        String valor="";
        cboxDist.removeAllItems();
        try{
            con.conectar();
            ResultSet rs = con.consulta("SELECT Cod_pvi FROM provincias WHERE Des_pvi='"+provi+"';");
            rs.next();
            valor=String.valueOf(rs.getObject("Cod_pvi"));
            //con.cierraConexion();
            dbcbox("SELECT Des_dst FROM distritos WHERE Cod_pvi='"+valor+"';",cboxDist);
        }catch(SQLException e){
            System.out.println(e);
        } 
    }//GEN-LAST:event_cboxProvItemStateChanged

    private void cboxProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxProvActionPerformed

    }//GEN-LAST:event_cboxProvActionPerformed

    private void cboxProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxProvKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxDist.requestFocus();
        }
    }//GEN-LAST:event_cboxProvKeyPressed

    private void cboxDistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxDistKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtDirec.requestFocus();
        }
    }//GEN-LAST:event_cboxDistKeyPressed

    private void txtDirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecActionPerformed
        // TODO add your handling code here:ç
    }//GEN-LAST:event_txtDirecActionPerformed

    private void txtDirecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirecKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            BtnGuardar.doClick();
        }
    }//GEN-LAST:event_txtDirecKeyPressed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        tipdoc=String.valueOf(cboxTipoDocum.getSelectedItem());
        sol = Integer.parseInt(lblUsu.getText());
        dni=this.txtNumDoc.getText();
        nom=txtNom.getText().toUpperCase();
        apePat=txtApePat.getText().toUpperCase();
        apeMat=txtApeMat.getText().toUpperCase();
        depart=String.valueOf(cboxDepart.getSelectedItem());
        prov=String.valueOf(cboxProv.getSelectedItem());
        distr=String.valueOf(cboxDist.getSelectedItem());
        direc=txtDirec.getText().toUpperCase();
        if(direc == null ? "" == null : direc.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Tiene que escribir su direccion Actual");
        }else{
            try{
                con.conectar();
                con.insertar("INSERT INTO usuarios ( nombre, apePat, apeMat, tipDoc, numDoc, direccion, codDep, codPro, codDis) "
                +" VALUES('"+nom+"','"+apePat+"','"+apeMat+"','"+tipdoc+"','"+dni+"','"+direc+"','"+depart+"','"+prov+"','"+distr+"');");
                //con.cierraConexion();
                dispose();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDNuevoUsuario dialog = new JDNuevoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction BtnCancelar;
    private org.edisoncor.gui.button.ButtonColoredAction BtnClose;
    private org.edisoncor.gui.button.ButtonColoredAction BtnGuardar;
    private javax.swing.JComboBox cboxDepart;
    private javax.swing.JComboBox cboxDist;
    private javax.swing.JComboBox cboxProv;
    private javax.swing.JComboBox cboxTipoDocum;
    private org.edisoncor.gui.label.LabelBackgroundTitle labelBackgroundTitle1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private org.edisoncor.gui.label.LabelMetric labelMetric9;
    private javax.swing.JLabel lblUsu;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTextField txtApeMat;
    private javax.swing.JTextField txtApePat;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables
}
