/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemasolicitudes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sistemasolicitudes.JFPrincipal;

/**
 *
 * @author digitacion-6
 */
public class JIFEnace extends javax.swing.JInternalFrame {
private static final long serialVersionUID = 1L;
    conexion con = new conexion();
    //Variables Globales
    int cod,idsol,not;
    String conPri, otor, favor, inst, lugar, año, otros, dia , mes, dni,ver_solicitud,NumIdSol,num_solicitud,codUsu;
    private ReporteEnace jasper;
    /**
     * Creates new form JIFEnace
     */
    public JIFEnace() {
        initComponents();
        llamar();
        desactiva();

    }
    public void llamar(){
                jasper=new ReporteEnace();

        txtSolicitud.setEditable(false);
//        lblIdSol.setVisible(false);
//        lblCod.setVisible(false);
//       labelMetric5.setVisible(false);
//        labelIdSol.setVisible(false);
//        //
        int solic=0,esc=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
                res.next();
                solic=Integer.parseInt(res.getString(1));
                res=con.consulta("SELECT count(idSol) FROM enace");
                res.next();
                esc=Integer.parseInt(res.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                System.out.println(e);
            }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
    }
    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(new Color(33,43,215,50));
        g.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
    }
    
        public void desactiva(){
       this.txtSolicitud.setText("");
       this.txtSolicitud.setEditable(false);
       this.txtNumDoc.setEditable(false);
       this.txtNom.setEditable(false);

        this.txtContrPriv.setEditable(false);
        this.txtOtor.setEditable(false);
        this.txtFavor.setEditable(false);
        this.txtInsti.setEditable(false);
        this.txtLugar.setEditable(false);
        this.txtdia.setEditable(false);
        this.txtAño.setEditable(false);
        this.txtOtros.setEditable(false);
            this.btnGuardar.setEnabled(false);
            this.btnImprimir.setEnabled(false);
            this.btnUsu.setEnabled(false);
        }
         public void activa(){
            this.txtSolicitud.setText("");
            this.txtSolicitud.setEditable(true);
            this.txtNumDoc.setEditable(true);
            this.txtNom.setEditable(true);
            this.txtContrPriv.setEditable(true);
        this.txtOtor.setEditable(true);
        this.txtFavor.setEditable(true);
        this.txtInsti.setEditable(true);
        this.txtLugar.setEditable(true);
        this.txtdia.setEditable(true);
        this.txtAño.setEditable(true);
        this.txtOtros.setEditable(true);
            this.btnGuardar.setEnabled(true);
            this.btnImprimir.setEnabled(true);
            this.btnUsu.setEnabled(true);
        }

      public void limpiar(){
        this.txtNumDoc.setText("");
        this.txtNom.setText("");
        this.lblCod.setText("");
        this.txtContrPriv.setText("");
        this.txtOtor.setText("");
        this.txtFavor.setText("");
        this.txtInsti.setText("");
        this.txtLugar.setText("");
        this.txtdia.setText("");
        this.txtAño.setText("");
        this.txtOtros.setText("");
        this.btnImprimir.setEnabled(false);
        desactiva();
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        txtNumDoc = new javax.swing.JTextField();
        btnUsu = new org.edisoncor.gui.button.ButtonAction();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        txtSolicitud = new javax.swing.JTextField();
        tabbedPaneHeader1 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelReflect1 = new org.edisoncor.gui.panel.PanelReflect();
        btnVer = new org.edisoncor.gui.button.ButtonColoredAction();
        BtnRImprimir = new org.edisoncor.gui.button.ButtonColoredAction();
        jSeparator1 = new javax.swing.JSeparator();
        buttonColoredAction1 = new org.edisoncor.gui.button.ButtonColoredAction();
        panelRectTranslucido2 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        txtNom = new javax.swing.JTextField();
        lblCod = new org.edisoncor.gui.label.LabelMetric();
        tabbedPaneHeader2 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelReflect2 = new org.edisoncor.gui.panel.PanelReflect();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric9 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric10 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric11 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric12 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric13 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric14 = new org.edisoncor.gui.label.LabelMetric();
        txtContrPriv = new javax.swing.JTextField();
        txtOtor = new javax.swing.JTextField();
        txtFavor = new javax.swing.JTextField();
        txtInsti = new javax.swing.JTextField();
        txtLugar = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        cboxMes = new javax.swing.JComboBox();
        txtAño = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        lblIdSol = new javax.swing.JLabel();
        labelIdSol = new javax.swing.JLabel();
        tabbedPaneHeader3 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelReflect3 = new org.edisoncor.gui.panel.PanelReflect();
        btnGuardar = new org.edisoncor.gui.button.ButtonColoredAction();
        btnImprimir = new org.edisoncor.gui.button.ButtonColoredAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        btnChangeDat = new org.edisoncor.gui.button.ButtonColoredAction();
        panelRoundTranslucido1 = new org.edisoncor.gui.panel.PanelRoundTranslucido();
        labelMetric18 = new org.edisoncor.gui.label.LabelMetric();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        setClosable(true);
        setIconifiable(true);

        panelImage1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(176, 177, 178)));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mageia-default-1920x1200.png"))); // NOI18N

        panelRectTranslucido1.setAnchoDeBorde(1.0F);
        panelRectTranslucido1.setAnchoDeSegundoBorde(1.0F);
        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido1.setColorDeSegundoBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido1.setMaximumSize(new java.awt.Dimension(620, 59));
        panelRectTranslucido1.setMinimumSize(new java.awt.Dimension(620, 59));

        labelMetric1.setText("N° Documento:");
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        txtNumDoc.setBackground(new java.awt.Color(1, 1, 1));
        txtNumDoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNumDoc.setForeground(new java.awt.Color(254, 254, 254));
        txtNumDoc.setToolTipText("");
        txtNumDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNumDoc.setMaximumSize(new java.awt.Dimension(287, 29));
        txtNumDoc.setMinimumSize(new java.awt.Dimension(287, 29));
        txtNumDoc.setPreferredSize(new java.awt.Dimension(287, 29));
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });

        btnUsu.setBackground(new java.awt.Color(1, 1, 1));
        btnUsu.setForeground(new java.awt.Color(56, 182, 54));
        btnUsu.setText("Buscar ");
        btnUsu.setColorDeSombra(new java.awt.Color(1, 1, 1));
        btnUsu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });

        labelMetric2.setText("N° Solicitud:");
        labelMetric2.setDistanciaDeSombra(2);

        txtSolicitud.setBackground(new java.awt.Color(1, 1, 1));
        txtSolicitud.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSolicitud.setForeground(new java.awt.Color(254, 254, 254));
        txtSolicitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSolicitud.setPreferredSize(new java.awt.Dimension(29, 19));

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneHeader1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnVer.setBackground(new java.awt.Color(0, 152, 76));
        btnVer.setText("Visualizar Solicitud");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        BtnRImprimir.setBackground(new java.awt.Color(0, 152, 76));
        BtnRImprimir.setText("Re-Imprimir Solicitud");
        BtnRImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRImprimirActionPerformed(evt);
            }
        });

        jSeparator1.setOpaque(true);

        buttonColoredAction1.setBackground(new java.awt.Color(43, 137, 182));
        buttonColoredAction1.setText("Nuevo");
        buttonColoredAction1.setMaximumSize(new java.awt.Dimension(175, 45));
        buttonColoredAction1.setMinimumSize(new java.awt.Dimension(175, 45));
        buttonColoredAction1.setPreferredSize(new java.awt.Dimension(175, 45));
        buttonColoredAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColoredAction1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReflect1Layout = new javax.swing.GroupLayout(panelReflect1);
        panelReflect1.setLayout(panelReflect1Layout);
        panelReflect1Layout.setHorizontalGroup(
            panelReflect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelReflect1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReflect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonColoredAction1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(BtnRImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReflect1Layout.setVerticalGroup(
            panelReflect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect1Layout.createSequentialGroup()
                .addComponent(buttonColoredAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneHeader1.addTab("OTROS", panelReflect1);

        panelRectTranslucido2.setAnchoDeBorde(1.0F);
        panelRectTranslucido2.setAnchoDeSegundoBorde(1.0F);
        panelRectTranslucido2.setColorDeBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido2.setColorDeSegundoBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido2.setMaximumSize(new java.awt.Dimension(807, 53));
        panelRectTranslucido2.setMinimumSize(new java.awt.Dimension(807, 53));
        panelRectTranslucido2.setPreferredSize(new java.awt.Dimension(807, 53));

        labelMetric3.setText("Nombre:");
        labelMetric3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        txtNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNom.setMaximumSize(new java.awt.Dimension(512, 29));
        txtNom.setMinimumSize(new java.awt.Dimension(512, 29));
        txtNom.setPreferredSize(new java.awt.Dimension(512, 29));
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });

        lblCod.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCod.setMaximumSize(new java.awt.Dimension(59, 29));
        lblCod.setMinimumSize(new java.awt.Dimension(59, 29));
        lblCod.setPreferredSize(new java.awt.Dimension(59, 29));

        javax.swing.GroupLayout panelRectTranslucido2Layout = new javax.swing.GroupLayout(panelRectTranslucido2);
        panelRectTranslucido2.setLayout(panelRectTranslucido2Layout);
        panelRectTranslucido2Layout.setHorizontalGroup(
            panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCod, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelRectTranslucido2Layout.setVerticalGroup(
            panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                        .addComponent(lblCod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabbedPaneHeader2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));

        labelMetric6.setText("Contrato Privado:");
        labelMetric6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        labelMetric7.setText("Otorgante:");
        labelMetric7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        labelMetric8.setText("Favorecido:");
        labelMetric8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        labelMetric9.setText("Institucion:");
        labelMetric9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        labelMetric10.setText("Año");
        labelMetric10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        labelMetric11.setText("Lugar:");
        labelMetric11.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        labelMetric12.setText("Dia");
        labelMetric12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        labelMetric13.setText("Mes");
        labelMetric13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        labelMetric14.setText("Fecha de contrato Privado");
        labelMetric14.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N

        txtContrPriv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContrPriv.setForeground(new java.awt.Color(1, 1, 1));
        txtContrPriv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrPrivKeyPressed(evt);
            }
        });

        txtOtor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtOtor.setForeground(new java.awt.Color(1, 1, 1));
        txtOtor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOtorKeyPressed(evt);
            }
        });

        txtFavor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFavor.setForeground(new java.awt.Color(1, 1, 1));
        txtFavor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFavorKeyPressed(evt);
            }
        });

        txtInsti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtInsti.setForeground(new java.awt.Color(1, 1, 1));
        txtInsti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstiKeyPressed(evt);
            }
        });

        txtLugar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLugar.setForeground(new java.awt.Color(1, 1, 1));
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLugarKeyPressed(evt);
            }
        });

        txtdia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdia.setForeground(new java.awt.Color(1, 1, 1));
        txtdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiaKeyPressed(evt);
            }
        });

        cboxMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxMes.setForeground(new java.awt.Color(1, 1, 1));
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });

        txtAño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAño.setForeground(new java.awt.Color(1, 1, 1));
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtOtros.setColumns(20);
        txtOtros.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtOtros.setRows(5);
        jScrollPane1.setViewportView(txtOtros);

        lblIdSol.setFont(new java.awt.Font("Ubuntu", 0, 1)); // NOI18N
        lblIdSol.setForeground(new java.awt.Color(45, 63, 95));

        labelIdSol.setText("labelIdSol");

        javax.swing.GroupLayout panelReflect2Layout = new javax.swing.GroupLayout(panelReflect2);
        panelReflect2.setLayout(panelReflect2Layout);
        panelReflect2Layout.setHorizontalGroup(
            panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect2Layout.createSequentialGroup()
                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContrPriv, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(txtOtor)
                                    .addComponent(txtFavor)
                                    .addComponent(txtInsti))))
                        .addGap(31, 31, 31))
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addComponent(labelIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLugar))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                        .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelReflect2Layout.setVerticalGroup(
            panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrPriv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabbedPaneHeader2.addTab("DATOS DEL NUEVO DOCUMENTO", panelReflect2);

        tabbedPaneHeader3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnGuardar.setBackground(new java.awt.Color(255, 197, 0));
        btnGuardar.setText("Guardar Datos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(255, 197, 0));
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("Cancelar");

        btnChangeDat.setBackground(new java.awt.Color(1, 1, 1));
        btnChangeDat.setText("Cambiar Datos");
        btnChangeDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReflect3Layout = new javax.swing.GroupLayout(panelReflect3);
        panelReflect3.setLayout(panelReflect3Layout);
        panelReflect3Layout.setHorizontalGroup(
            panelReflect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReflect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(btnChangeDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReflect3Layout.setVerticalGroup(
            panelReflect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect3Layout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnChangeDat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPaneHeader3.addTab("OPCIONES", panelReflect3);

        labelMetric18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric18.setText("ENACE");
        labelMetric18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelRoundTranslucido1Layout = new javax.swing.GroupLayout(panelRoundTranslucido1);
        panelRoundTranslucido1.setLayout(panelRoundTranslucido1Layout);
        panelRoundTranslucido1Layout.setHorizontalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMetric18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRoundTranslucido1Layout.setVerticalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundTranslucido1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMetric18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabbedPaneHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRectTranslucido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabbedPaneHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbedPaneHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRectTranslucido2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbedPaneHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        getContentPane().add(panelImage1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonColoredAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColoredAction1ActionPerformed
        activa();
        this.txtNumDoc.requestFocus();
        int solic=0,esc=0;
        try{
            con.conectar();
            ResultSet res=con.consulta("SELECT max(codSol) FROM solicitudes");
            res.next();
            solic=Integer.parseInt(res.getString(1));
            res=con.consulta("SELECT count(idSol) FROM enace");
            res.next();
            esc=Integer.parseInt(res.getString(1));
            con.cierraConexion();
        }catch(SQLException e){
            System.out.println(e);
        }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        this.txtNumDoc.setText("");
        this.txtNom.setText("");
        this.lblCod.setText("");
        this.txtContrPriv.setText("");
        this.txtOtor.setText("");
        this.txtFavor.setText("");
        this.txtInsti.setText("");
        this.txtLugar.setText("");
        this.txtdia.setText("");
        this.txtAño.setText("");
        this.txtOtros.setText("");
    }//GEN-LAST:event_buttonColoredAction1ActionPerformed

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtContrPriv.requestFocus();
        }
    }//GEN-LAST:event_txtNomKeyPressed

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
        int numero = txtNumDoc.getText().length();
        String dni2 ="";
        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros");
            this.txtNumDoc.requestFocus();
        }else{
            dni=txtNumDoc.getText();
            try{
                con.conectar();
                ResultSet rs=con.consulta("SELECT CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre, codUsu FROM usuarios WHERE numDoc='"+dni+"' LIMIT 0,1;");
                rs.next();
                txtNom.setText(rs.getString("nombre"));
                lblCod.setText(rs.getString("codUsu"));
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
               JFPrincipal.DNI = this.txtNumDoc.getText();
                JDNuevoUsuario p=new JDNuevoUsuario(null, true);
                p.setVisible(true);
            }
//            txtContrPriv.requestFocus();
        }
    }//GEN-LAST:event_btnUsuActionPerformed

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyPressed

    private void btnChangeDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDatActionPerformed
        codUsu = this.labelIdSol.getText();
        idsol =Integer.parseInt(lblIdSol.getText());
        // Recoje los datos
        NumIdSol = this.labelIdSol.getText();
        num_solicitud = this.txtSolicitud.getText();

        conPri=this.txtContrPriv.getText().toUpperCase();
        otor = this.txtOtor.getText().toUpperCase();
        favor = this.txtFavor.getText().toUpperCase();
        inst = this.txtInsti.getText().toUpperCase();
        lugar=this.txtLugar.getText().toUpperCase();
        dia = this.txtdia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        año = this.txtAño.getText().toUpperCase();
        otros = this.txtOtros.getText().toUpperCase();

        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE `recepcion`.`enace` SET `conPri`='"+conPri+"', `otorgante`='"+otor+"', `favorecido`='"+favor+"', `institucion`='"+inst+"', `lugar`='"+lugar+"', `dia`='"+dia+"', `mes`='"+mes+"', `anio`='"+año+"', `obs`='"+otros+"'WHERE idSol = '"+NumIdSol+"';");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+codUsu+"', idSol = '"+NumIdSol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        this.btnChangeDat.setVisible(false);
        this.btnGuardar.setVisible(true);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
    }//GEN-LAST:event_btnChangeDatActionPerformed

    private void BtnRImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRImprimirActionPerformed
        String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        String num_sol = solicitudD;
        jasper.ejecutarReporte(num_sol);
    }//GEN-LAST:event_BtnRImprimirActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);
        this.txtContrPriv.setEditable(true);
        this.txtFavor.setEditable(true);
        this.txtOtor.setEditable(true);
        this.txtInsti.setEditable(true);
        this.txtOtros.setEditable(true);
        this.txtdia.setEditable(true);

        this.cboxMes.setSelectedIndex(0);
        this.txtAño.setEditable(true);

        this.txtLugar.setEditable(true);

        this.btnGuardar.setVisible(false);
        this.btnChangeDat.setVisible(true);
        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol, s.idSol, CONCAT(u.nombre,' ', u.apePat,' ',apeMat) AS usuario,u.codUsu, u.codDis, u.numDoc, u.direccion,en.conPri, en.otorgante, en.favorecido, en.institucion, en.lugar, en.dia, en.mes, en.anio, en.obs FROM solicitudes AS s, usuarios AS u,enace AS en WHERE s.idSol = en.idSol AND s.codUsu = u.codUsu AND s.codSol = '"+ver_solicitud+"';");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol"));
            this.txtNumDoc.setText(res.getString("numDoc"));
            this.lblCod.setText(res.getString("codUsu"));
            this.txtNom.setText(res.getString("usuario"));

            this.txtContrPriv.setText(res.getString("conPri"));
            this.txtOtor.setText(res.getString("otorgante"));
            this.txtFavor.setText(res.getString("favorecido"));
            this.txtInsti.setText(res.getString("institucion"));
            this.txtLugar.setText(res.getString("Lugar"));
            this.txtdia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtOtros.setText(res.getString("obs"));
            //            this.labelIdSol.setText(res.getString("idSol"));
            con.cierraConexion();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error Consultando. " + e);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtros.requestFocus();
        }
    }//GEN-LAST:event_txtAñoKeyPressed

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
    }//GEN-LAST:event_cboxMesKeyPressed

    private void txtdiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.cboxMes.requestFocus();
        }
    }//GEN-LAST:event_txtdiaKeyPressed

    private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtdia.requestFocus();
        }
    }//GEN-LAST:event_txtLugarKeyPressed

    private void txtInstiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstiKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtLugar.requestFocus();
        }
    }//GEN-LAST:event_txtInstiKeyPressed

    private void txtFavorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFavorKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtInsti.requestFocus();
        }
    }//GEN-LAST:event_txtFavorKeyPressed

    private void txtOtorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtorKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtFavor.requestFocus();
        }
    }//GEN-LAST:event_txtOtorKeyPressed

    private void txtContrPrivKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrPrivKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtor.requestFocus();
        }
    }//GEN-LAST:event_txtContrPrivKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction BtnRImprimir;
    private org.edisoncor.gui.button.ButtonColoredAction btnCancelar;
    private org.edisoncor.gui.button.ButtonColoredAction btnChangeDat;
    private org.edisoncor.gui.button.ButtonColoredAction btnGuardar;
    private org.edisoncor.gui.button.ButtonColoredAction btnImprimir;
    private org.edisoncor.gui.button.ButtonAction btnUsu;
    private org.edisoncor.gui.button.ButtonColoredAction btnVer;
    private org.edisoncor.gui.button.ButtonColoredAction buttonColoredAction1;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelIdSol;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric10;
    private org.edisoncor.gui.label.LabelMetric labelMetric11;
    private org.edisoncor.gui.label.LabelMetric labelMetric12;
    private org.edisoncor.gui.label.LabelMetric labelMetric13;
    private org.edisoncor.gui.label.LabelMetric labelMetric14;
    private org.edisoncor.gui.label.LabelMetric labelMetric18;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private org.edisoncor.gui.label.LabelMetric labelMetric9;
    private org.edisoncor.gui.label.LabelMetric lblCod;
    private javax.swing.JLabel lblIdSol;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido2;
    private org.edisoncor.gui.panel.PanelReflect panelReflect1;
    private org.edisoncor.gui.panel.PanelReflect panelReflect2;
    private org.edisoncor.gui.panel.PanelReflect panelReflect3;
    private org.edisoncor.gui.panel.PanelRoundTranslucido panelRoundTranslucido1;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader1;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader2;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader3;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtContrPriv;
    private javax.swing.JTextField txtFavor;
    private javax.swing.JTextField txtInsti;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtOtor;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtdia;
    // End of variables declaration//GEN-END:variables
}
