/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemasolicitudes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author digitacion-6
 */
public class JIFProNoContencioso extends javax.swing.JInternalFrame {
    conexion con = new conexion();
    int cod,idsol,not, notario;
    //
    String proc, seguido, contra, causante, lugar, año, otros, num_solicitud, dia, mes, ver_solicitud, codUsu;
    private ReporteProcNoContencioso jasper;
    /**
     * Creates new form JIFProNoContencioso
     */
    public JIFProNoContencioso() {
        initComponents();
        desactiva();
        jasper=new ReporteProcNoContencioso();        
        try{
            this.dbcbox("SELECT CONCAT(pat_not,' ',mat_not,' ',nom_not) AS notario FROM notarios;",cboxNotario);
        }catch(Exception e){
            System.out.println(e+"mal");
        }
        //
        int solic=0,esc=0;
        try{
                con.conectar();
                ResultSet res=con.consulta("SELECT COUNT(codSol) FROM solicitudes;");
                res.next();
                solic=Integer.parseInt(res.getString(1));
                res=con.consulta("SELECT COUNT(idSol) FROM procontenciosos;");
                res.next();
                esc=Integer.parseInt(res.getString(1));
                con.cierraConexion();
            }catch(SQLException e){
                System.out.println(e);
            }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
    }
    protected void paintComponent(Graphics g) {
        g.setColor(new Color(255,0,0,50));
        g.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
    }
    
        public void dbcbox(String sql,JComboBox a){
            try {
                con.conectar();
                ResultSet rs = con.consulta(sql);
                while(rs.next()){
                    a.addItem (rs.getObject(1));
                }
                rs.close();
            } catch (SQLException e) {
                 System.out.println(e);
            }
        }
    public void desactiva(){
            this.txtSolicitud.setText("");
            this.txtSolicitud.setEditable(false);
            this.txtNumDoc.setEditable(false);
            this.txtNom.setEditable(false);
            this.btnGuardar.setEnabled(false);
            this.btnImprimir.setEnabled(false);
            this.btnUsu.setEnabled(false);
        }
    public void activa(){
            //this.txtSolicitud.setText("");
            this.txtNumDoc.setEditable(true);
            this.txtNom.setEditable(true);
            this.btnGuardar.setEnabled(true);
            //this.btnImprimir.setEnabled(true);
            this.btnUsu.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelRoundTranslucido1 = new org.edisoncor.gui.panel.PanelRoundTranslucido();
        labelMetric18 = new org.edisoncor.gui.label.LabelMetric();
        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        txtNumDoc = new javax.swing.JTextField();
        btnUsu = new org.edisoncor.gui.button.ButtonAction();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        txtSolicitud = new javax.swing.JTextField();
        panelRectTranslucido2 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        txtNom = new javax.swing.JTextField();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        lblCod = new org.edisoncor.gui.label.LabelMetric();
        tabbedPaneHeader2 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelReflect2 = new org.edisoncor.gui.panel.PanelReflect();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric8 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric9 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric10 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric11 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric12 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric13 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric14 = new org.edisoncor.gui.label.LabelMetric();
        txtdia = new javax.swing.JTextField();
        cboxMes = new javax.swing.JComboBox();
        txtAño = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtros = new javax.swing.JTextArea();
        lblIdSol = new javax.swing.JLabel();
        LabelIdSol = new javax.swing.JLabel();
        cboxNotario = new javax.swing.JComboBox();
        txtCausante = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        txtSeguido = new javax.swing.JTextField();
        txtPro = new javax.swing.JTextField();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        txtLugar = new javax.swing.JTextField();
        tabbedPaneHeader1 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelReflect1 = new org.edisoncor.gui.panel.PanelReflect();
        btnVisualizar = new org.edisoncor.gui.button.ButtonColoredAction();
        BtnRImprimir = new org.edisoncor.gui.button.ButtonColoredAction();
        jSeparator1 = new javax.swing.JSeparator();
        BtnNuevo = new org.edisoncor.gui.button.ButtonColoredAction();
        tabbedPaneHeader3 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        panelReflect3 = new org.edisoncor.gui.panel.PanelReflect();
        btnGuardar = new org.edisoncor.gui.button.ButtonColoredAction();
        btnImprimir = new org.edisoncor.gui.button.ButtonColoredAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        btnCambiarDatos = new org.edisoncor.gui.button.ButtonColoredAction();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));
        setClosable(true);
        setIconifiable(true);

        panelImage1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(176, 177, 178)));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wall-rojizo-5645.jpg"))); // NOI18N

        labelMetric18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric18.setText("PROCESO NO CONTENCIOSOS");
        labelMetric18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout panelRoundTranslucido1Layout = new javax.swing.GroupLayout(panelRoundTranslucido1);
        panelRoundTranslucido1.setLayout(panelRoundTranslucido1Layout);
        panelRoundTranslucido1Layout.setHorizontalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMetric18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRoundTranslucido1Layout.setVerticalGroup(
            panelRoundTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundTranslucido1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMetric18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelRectTranslucido1.setAnchoDeBorde(1.0F);
        panelRectTranslucido1.setAnchoDeSegundoBorde(1.0F);
        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido1.setColorDeSegundoBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido1.setMaximumSize(new java.awt.Dimension(620, 59));
        panelRectTranslucido1.setMinimumSize(new java.awt.Dimension(620, 59));

        labelMetric1.setText("N° Documento:");
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        txtNumDoc.setBackground(new java.awt.Color(1, 1, 1));
        txtNumDoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNumDoc.setForeground(new java.awt.Color(254, 254, 254));
        txtNumDoc.setToolTipText("");
        txtNumDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNumDoc.setMaximumSize(new java.awt.Dimension(287, 29));
        txtNumDoc.setMinimumSize(new java.awt.Dimension(287, 29));
        txtNumDoc.setPreferredSize(new java.awt.Dimension(287, 29));
        txtNumDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumDocKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocKeyTyped(evt);
            }
        });

        btnUsu.setBackground(new java.awt.Color(1, 1, 1));
        btnUsu.setForeground(new java.awt.Color(56, 182, 54));
        btnUsu.setText("Buscar ");
        btnUsu.setColorDeSombra(new java.awt.Color(1, 1, 1));
        btnUsu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });

        labelMetric2.setText("N° Solicitud:");
        labelMetric2.setDistanciaDeSombra(2);

        txtSolicitud.setBackground(new java.awt.Color(1, 1, 1));
        txtSolicitud.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSolicitud.setForeground(new java.awt.Color(254, 254, 254));
        txtSolicitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtSolicitud.setPreferredSize(new java.awt.Dimension(29, 19));

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRectTranslucido2.setAnchoDeBorde(1.0F);
        panelRectTranslucido2.setAnchoDeSegundoBorde(1.0F);
        panelRectTranslucido2.setColorDeBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido2.setColorDeSegundoBorde(new java.awt.Color(176, 177, 178));
        panelRectTranslucido2.setMaximumSize(new java.awt.Dimension(807, 53));
        panelRectTranslucido2.setMinimumSize(new java.awt.Dimension(807, 53));

        labelMetric3.setText("Nombre:");
        labelMetric3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        txtNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNom.setMaximumSize(new java.awt.Dimension(512, 29));
        txtNom.setMinimumSize(new java.awt.Dimension(512, 29));
        txtNom.setPreferredSize(new java.awt.Dimension(512, 29));
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomKeyPressed(evt);
            }
        });

        labelMetric5.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N

        lblCod.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCod.setMaximumSize(new java.awt.Dimension(59, 29));
        lblCod.setMinimumSize(new java.awt.Dimension(59, 29));
        lblCod.setPreferredSize(new java.awt.Dimension(59, 29));

        javax.swing.GroupLayout panelRectTranslucido2Layout = new javax.swing.GroupLayout(panelRectTranslucido2);
        panelRectTranslucido2.setLayout(panelRectTranslucido2Layout);
        panelRectTranslucido2Layout.setHorizontalGroup(
            panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMetric5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCod, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        panelRectTranslucido2Layout.setVerticalGroup(
            panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido2Layout.createSequentialGroup()
                        .addComponent(lblCod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMetric5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabbedPaneHeader2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 177, 178)));

        labelMetric6.setText("Proceso de:");
        labelMetric6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelMetric7.setText("Seguido por:");
        labelMetric7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelMetric8.setText("En contra de:");
        labelMetric8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelMetric9.setText("Causante:");
        labelMetric9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelMetric10.setText("Año");
        labelMetric10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        labelMetric11.setText("Lugar:");
        labelMetric11.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        labelMetric12.setText("Dia");
        labelMetric12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        labelMetric13.setText("Mes");
        labelMetric13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        labelMetric14.setText("Fecha del Proceso");
        labelMetric14.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N

        txtdia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdia.setForeground(new java.awt.Color(1, 1, 1));
        txtdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiaKeyPressed(evt);
            }
        });

        cboxMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboxMes.setForeground(new java.awt.Color(1, 1, 1));
        cboxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cboxMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxMesKeyPressed(evt);
            }
        });

        txtAño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAño.setForeground(new java.awt.Color(1, 1, 1));
        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtOtros.setColumns(20);
        txtOtros.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtOtros.setRows(5);
        jScrollPane1.setViewportView(txtOtros);

        cboxNotario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxNotario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cboxNotario.setMaximumSize(new java.awt.Dimension(333, 25));
        cboxNotario.setMinimumSize(new java.awt.Dimension(333, 25));
        cboxNotario.setPreferredSize(new java.awt.Dimension(333, 25));
        cboxNotario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboxNotarioKeyPressed(evt);
            }
        });

        txtCausante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCausante.setMaximumSize(new java.awt.Dimension(333, 25));
        txtCausante.setMinimumSize(new java.awt.Dimension(333, 25));
        txtCausante.setPreferredSize(new java.awt.Dimension(333, 25));
        txtCausante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCausanteKeyPressed(evt);
            }
        });

        txtContra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContra.setMaximumSize(new java.awt.Dimension(333, 25));
        txtContra.setMinimumSize(new java.awt.Dimension(333, 25));
        txtContra.setPreferredSize(new java.awt.Dimension(333, 25));
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });

        txtSeguido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSeguido.setMaximumSize(new java.awt.Dimension(333, 25));
        txtSeguido.setMinimumSize(new java.awt.Dimension(333, 25));
        txtSeguido.setPreferredSize(new java.awt.Dimension(333, 25));
        txtSeguido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeguidoKeyPressed(evt);
            }
        });

        txtPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPro.setMaximumSize(new java.awt.Dimension(333, 25));
        txtPro.setMinimumSize(new java.awt.Dimension(333, 25));
        txtPro.setPreferredSize(new java.awt.Dimension(333, 25));
        txtPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProKeyPressed(evt);
            }
        });

        labelMetric4.setText("Notario:");
        labelMetric4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtLugar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLugarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelReflect2Layout = new javax.swing.GroupLayout(panelReflect2);
        panelReflect2.setLayout(panelReflect2Layout);
        panelReflect2Layout.setHorizontalGroup(
            panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect2Layout.createSequentialGroup()
                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMetric7, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(labelMetric6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeguido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addComponent(LabelIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelReflect2Layout.createSequentialGroup()
                                    .addComponent(labelMetric4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(panelReflect2Layout.createSequentialGroup()
                                    .addComponent(labelMetric9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(12, 12, 12)))
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCausante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxNotario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21)
                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugar))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                        .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelReflect2Layout.setVerticalGroup(
            panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(labelMetric14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelMetric12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMetric11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(panelReflect2Layout.createSequentialGroup()
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReflect2Layout.createSequentialGroup()
                                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49))
                            .addGroup(panelReflect2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSeguido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMetric9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCausante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelReflect2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxNotario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(LabelIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblIdSol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabbedPaneHeader2.addTab("DATOS DEL DOCUMENTO", panelReflect2);

        tabbedPaneHeader1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnVisualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnVisualizar.setText("Visualizar Proceso");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        BtnRImprimir.setBackground(new java.awt.Color(0, 0, 0));
        BtnRImprimir.setText("Re-Imprimir");
        BtnRImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRImprimirActionPerformed(evt);
            }
        });

        jSeparator1.setOpaque(true);

        BtnNuevo.setBackground(new java.awt.Color(43, 137, 182));
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setMaximumSize(new java.awt.Dimension(175, 45));
        BtnNuevo.setMinimumSize(new java.awt.Dimension(175, 45));
        BtnNuevo.setPreferredSize(new java.awt.Dimension(175, 45));
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReflect1Layout = new javax.swing.GroupLayout(panelReflect1);
        panelReflect1.setLayout(panelReflect1Layout);
        panelReflect1Layout.setHorizontalGroup(
            panelReflect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelReflect1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReflect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(BtnRImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReflect1Layout.setVerticalGroup(
            panelReflect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect1Layout.createSequentialGroup()
                .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneHeader1.addTab("OTROS", panelReflect1);

        tabbedPaneHeader3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnGuardar.setBackground(new java.awt.Color(0, 255, 44));
        btnGuardar.setText("Guardar Datos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(0, 255, 44));
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(244, 220, 106));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCambiarDatos.setBackground(new java.awt.Color(1, 1, 1));
        btnCambiarDatos.setText("Cambiar Datos");
        btnCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReflect3Layout = new javax.swing.GroupLayout(panelReflect3);
        panelReflect3.setLayout(panelReflect3Layout);
        panelReflect3Layout.setHorizontalGroup(
            panelReflect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReflect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(btnCambiarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelReflect3Layout.setVerticalGroup(
            panelReflect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReflect3Layout.createSequentialGroup()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPaneHeader3.addTab("OPCIONES", panelReflect3);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabbedPaneHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRectTranslucido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabbedPaneHeader3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRoundTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRectTranslucido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbedPaneHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(tabbedPaneHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbedPaneHeader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(panelImage1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyPressed

    private void txtNumDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyReleased
        if(txtNumDoc.getText().length()>7){
            btnUsu.doClick();
        }
    }//GEN-LAST:event_txtNumDocKeyReleased

    private void txtNumDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocKeyTyped
        int n = (int)evt.getKeyChar();
        if(n>=48 && n<=57 || n==13 || n==127){

        }else{
            evt.setKeyChar((char)KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtNumDocKeyTyped

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
             int numero = txtNumDoc.getText().length();
        String dni2 ="";
        if (numero <8){
            JOptionPane.showMessageDialog(rootPane, "Numero de Digitos de DNI Menor que 8 Numeros");
            this.txtNumDoc.requestFocus();
        }else{
            int dni=Integer.parseInt(txtNumDoc.getText());
            try{
                con.conectar();
                ResultSet rs=con.consulta("SELECT CONCAT(nombre,' ',apePat,' ',apeMat) AS nombre, codUsu FROM usuarios WHERE numDoc="+dni+" LIMIT 0,1;");
                rs.next();
                txtNom.setText(rs.getString("nombre"));
                lblCod.setText(rs.getString("codUsu"));
            }catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado","Administrador de Sistema",JOptionPane.INFORMATION_MESSAGE);
                JFPrincipal.DNI = this.txtNumDoc.getText();
                JDNuevoUsuario p=new JDNuevoUsuario(null, true);
                p.setVisible(true);
            }
            txtPro.requestFocus();
        }
    }//GEN-LAST:event_btnUsuActionPerformed

    private void txtNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtPro.requestFocus();
        }
    }//GEN-LAST:event_txtNomKeyPressed

    private void txtdiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiaKeyPressed
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            this.cboxMes.requestFocus();
        }
    }//GEN-LAST:event_txtdiaKeyPressed

    private void cboxMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxMesKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtAño.requestFocus();
        }
    }//GEN-LAST:event_cboxMesKeyPressed

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtOtros.requestFocus();
        }
    }//GEN-LAST:event_txtAñoKeyPressed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        ver_solicitud = JOptionPane.showInputDialog("Ingrese Numero de Solicitud a visualizar");

        this.txtNumDoc.setEditable(true);
        this.btnUsu.setEnabled(true);

        this.btnGuardar.setVisible(false);
        this.btnCambiarDatos.setVisible(true);

        try{
            con.conectar();
            ResultSet res = con.consulta("SELECT s.codSol,s.idSol, CONCAT(u.nombre,' ',u.apePat,' ',u.apeMat)as usuario,u.codUsu, u.codDis,u.numDoc, u.direccion,pc.tipPro,pc.seguido,pc.contra,pc.causante,CONCAT(n.nom_not,' ',n.pat_not,' ',n.mat_not) as notario,pc.lugar,pc.dia,pc.mes,pc.anio,pc.obs FROM solicitudes AS s, usuarios AS u, procontenciosos as pc, notarios as n WHERE s.codUsu = u.codUsu  and s.idSol=pc.idSol and pc.codNot=n.cod_not and s.codSol ="+ver_solicitud+";");
            res.next();
            this.txtSolicitud.setText(res.getString("codSol").toString());
            this.txtNumDoc.setText(res.getString("numDoc").toString());
            this.txtNom.setText(res.getString("usuario"));

            this.txtPro.setText(res.getString("tipPro"));
            this.txtSeguido.setText(res.getString("seguido"));
            this.txtContra.setText(res.getString("contra"));
            this.txtCausante.setText(res.getString("causante"));
            this.cboxNotario.setSelectedItem(res.getString("notario"));
            this.txtLugar.setText(res.getString("lugar"));
            this.txtdia.setText(res.getString("dia"));
            this.cboxMes.setSelectedItem(res.getString("mes"));
            this.txtAño.setText(res.getString("anio"));
            this.txtOtros.setText(res.getString("obs"));
            this.LabelIdSol.setText(res.getString("idSol"));
            this.lblCod.setText(res.getString("codUsu"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void BtnRImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRImprimirActionPerformed
       String solicitudD = JOptionPane.showInputDialog("Escriba el Numero de Solicitud");
        String num_sol = solicitudD;
        jasper.ejecutarReporte(num_sol);
    }//GEN-LAST:event_BtnRImprimirActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        activa();
        txtNumDoc.requestFocus();
        int solic=0,esc=0;
        try{
            con.conectar();
            ResultSet res=con.consulta("SELECT MAX(codSol) FROM solicitudes;");
            res.next();
            solic=Integer.parseInt(res.getString(1));
            res=con.consulta("SELECT COUNT(idSol) FROM procontenciosos;");
            res.next();
            esc=Integer.parseInt(res.getString(1));
            con.cierraConexion();
        }catch(SQLException e){
            System.out.println(e);
        }
        txtSolicitud.setText(String.valueOf(solic+1));
        lblIdSol.setText(String.valueOf(esc+1));
        txtNom.setText("");
        txtNumDoc.setText("");;
        txtOtros.setText("");
        this.txtdia.getText();
        cboxMes.setSelectedIndex(0);
        txtAño.setText("");
        txtPro.setText("");
        txtSeguido.setText("");
        txtContra.setText("");
        txtCausante.setText("");
        cboxNotario.setSelectedIndex(0);
        txtLugar.setText("");
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
              cod = Integer.parseInt(lblCod.getText());
        idsol =Integer.parseInt(lblIdSol.getText());
        int codTipSol=6;
        //
        num_solicitud = this.txtSolicitud.getText();
        proc = txtPro.getText().toUpperCase();
        not = this.cboxNotario.getSelectedIndex();
        seguido = txtSeguido.getText().toUpperCase();
        contra = txtContra.getText().toUpperCase();
        causante = txtCausante.getText().toUpperCase();
        lugar = txtLugar.getText().toUpperCase();
        dia = this.txtdia.getText();
        mes = this.cboxMes.getSelectedItem().toString();
        año = txtAño.getText();
        otros = txtOtros.getText().toUpperCase();

        if(not ==0){
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar Notario.  Si no hay Notario presione el Signo Menos\"-\" para Ninguno.");
        }else{
            int rpta = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de Guardar?","ARP Sistema",JOptionPane.YES_NO_OPTION);
            if(rpta == 0){
            try{
                con.conectar();
                con.insertar("INSERT INTO procontenciosos(tipPro,seguido,contra,causante,codNot,lugar,dia,mes,anio,obs) "
                        + "VALUES ('"+proc+"','"+seguido+"','"+contra+"','"+causante+"','"+not+"','"+lugar+"','"+dia+"','"+mes+"','"+año+"','"+otros+"');");
                con.insertar("INSERT INTO solicitudes(codSol,codUsu,codTipSol,idSol) VALUES ('"+num_solicitud+"','"+cod+"','"+codTipSol+"','"+idsol+"');");
                con.cierraConexion();
            
                this.btnGuardar.setEnabled(false);
                this.btnImprimir.setEnabled(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String num_sol = txtSolicitud.getText();
        jasper.ejecutarReporte(num_sol);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarDatosActionPerformed
        codUsu = this.lblCod.getText();   //Codigo del usuario
        idsol =Integer.parseInt(this.LabelIdSol.getText());   //

        num_solicitud = this.txtSolicitud.getText();

        proc=this.txtPro.getText().toUpperCase();
        seguido=this.txtSeguido.getText().toUpperCase();
        contra=this.txtContra.getText().toUpperCase();
        causante = this.txtCausante.getText().toUpperCase();
        not=this.cboxNotario.getSelectedIndex();
        lugar = this.txtLugar.getText().toUpperCase();
        dia = this.txtdia.getText().toUpperCase();
        mes = this.cboxMes.getSelectedItem().toString();
        año = txtAño.getText().toUpperCase();
        otros = txtOtros.getText().toUpperCase();

        if(not == 0){
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un Notario. Si no hay Notario, presione el signo menos \"-\", para seleccionar ninguno.\nConsulte con el Adminsitrador del sistema.");
        }
        else{
        int rpta1 = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro de realizar estos cambios?","ARP Sistema",JOptionPane.YES_NO_OPTION);
        if(rpta1 == 0){
            try{
                con.conectar();
                con.actualizar("UPDATE procontenciosos SET `tipPro`='"+proc+"', `seguido`='"+seguido+"', `contra`='"+contra+"', `causante`='"+causante+"', `codNot`='"+not+"', `lugar`='"+lugar+"', `dia`='"+dia+"', `mes`='"+mes+"', `anio`='"+año+"', `obs`='"+otros+"' WHERE `idSol`='"+idsol+"';");
                con.actualizar("UPDATE solicitudes SET codUsu = '"+codUsu+"', idSol = '"+idsol+"' WHERE codSol = '"+num_solicitud+"';");
                JOptionPane.showMessageDialog(rootPane, "Datos Modificados Satisfactotiamente");
                //con.cierraConexion();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error Cambiando datos. " + e);
            }
        }
        
        this.btnCambiarDatos.setVisible(false);
        this.btnGuardar.setEnabled(false);
        this.btnImprimir.setEnabled(true);
        }
    }//GEN-LAST:event_btnCambiarDatosActionPerformed

    private void cboxNotarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboxNotarioKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtLugar.requestFocus();
        }
    }//GEN-LAST:event_cboxNotarioKeyPressed

    private void txtCausanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCausanteKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            cboxNotario.requestFocus();
        }
    }//GEN-LAST:event_txtCausanteKeyPressed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtCausante.requestFocus();
        }
    }//GEN-LAST:event_txtContraKeyPressed

    private void txtSeguidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguidoKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtContra.requestFocus();
        }
    }//GEN-LAST:event_txtSeguidoKeyPressed

    private void txtProKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtSeguido.requestFocus();
        }
    }//GEN-LAST:event_txtProKeyPressed

    private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            txtdia.requestFocus();
        }
    }//GEN-LAST:event_txtLugarKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction BtnNuevo;
    private org.edisoncor.gui.button.ButtonColoredAction BtnRImprimir;
    private javax.swing.JLabel LabelIdSol;
    private org.edisoncor.gui.button.ButtonColoredAction btnCambiarDatos;
    private org.edisoncor.gui.button.ButtonColoredAction btnCancelar;
    private org.edisoncor.gui.button.ButtonColoredAction btnGuardar;
    private org.edisoncor.gui.button.ButtonColoredAction btnImprimir;
    private org.edisoncor.gui.button.ButtonAction btnUsu;
    private org.edisoncor.gui.button.ButtonColoredAction btnVisualizar;
    private javax.swing.JComboBox cboxMes;
    private javax.swing.JComboBox cboxNotario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric10;
    private org.edisoncor.gui.label.LabelMetric labelMetric11;
    private org.edisoncor.gui.label.LabelMetric labelMetric12;
    private org.edisoncor.gui.label.LabelMetric labelMetric13;
    private org.edisoncor.gui.label.LabelMetric labelMetric14;
    private org.edisoncor.gui.label.LabelMetric labelMetric18;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private org.edisoncor.gui.label.LabelMetric labelMetric8;
    private org.edisoncor.gui.label.LabelMetric labelMetric9;
    private org.edisoncor.gui.label.LabelMetric lblCod;
    private javax.swing.JLabel lblIdSol;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido2;
    private org.edisoncor.gui.panel.PanelReflect panelReflect1;
    private org.edisoncor.gui.panel.PanelReflect panelReflect2;
    private org.edisoncor.gui.panel.PanelReflect panelReflect3;
    private org.edisoncor.gui.panel.PanelRoundTranslucido panelRoundTranslucido1;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader1;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader2;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader3;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCausante;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextArea txtOtros;
    private javax.swing.JTextField txtPro;
    private javax.swing.JTextField txtSeguido;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtdia;
    // End of variables declaration//GEN-END:variables
}
